rubyonrail/friend/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :friend_data
  resources :friends
  get 'home/about'
  root 'home#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

rubyonrail/friend/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

rubyonrail/friend/app/models/friend.rb
class Friend < ApplicationRecord
end

rubyonrail/friend/app/models/friend_datum.rb
class FriendDatum < ApplicationRecord
    belongs_to :user
end

rubyonrail/friend/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
        has_many :friend_data
end

rubyonrail/friend/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

rubyonrail/friend/app/controllers/friend_data_controller.rb
class FriendDataController < ApplicationController
  before_action :set_friend_datum, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: [:index, :show]

  # GET /friend_data or /friend_data.json
  def index
    @friend_data = FriendDatum.all
  end

  # GET /friend_data/1 or /friend_data/1.json
  def show
  end

  # GET /friend_data/new
  def new
    @friend_datum = FriendDatum.new
  end

  # GET /friend_data/1/edit
  def edit
  end

  # POST /friend_data or /friend_data.json
  def create
    @friend_datum = FriendDatum.new(friend_datum_params)

    respond_to do |format|
      if @friend_datum.save
        format.html { redirect_to @friend_datum, notice: "Friend datum was successfully created." }
        format.json { render :show, status: :created, location: @friend_datum }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @friend_datum.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /friend_data/1 or /friend_data/1.json
  def update
    respond_to do |format|
      if @friend_datum.update(friend_datum_params)
        format.html { redirect_to @friend_datum, notice: "Friend datum was successfully updated." }
        format.json { render :show, status: :ok, location: @friend_datum }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @friend_datum.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /friend_data/1 or /friend_data/1.json
  def destroy
    @friend_datum.destroy
    respond_to do |format|
      format.html { redirect_to friend_data_url, notice: "Friend datum was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_friend_datum
      @friend_datum = FriendDatum.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def friend_datum_params
      params.require(:friend_datum).permit(:firtName, :lastName, :email, :phone, :user_id)
    end
end

rubyonrail/friend/app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def about
  end
end

rubyonrail/friend/app/helpers/application_helper.rb
module ApplicationHelper
end

rubyonrail/friend/app/helpers/friend_data_helper.rb
module FriendDataHelper
end

rubyonrail/friend/app/helpers/friends_helper.rb
module FriendsHelper
end

rubyonrail/friend/app/helpers/home_helper.rb
module HomeHelper
end

rubyonrail/friend/app/views/friend_data/_form.html.erb
<%= form_with(model: friend_datum) do |form| %>
  <% if friend_datum.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(friend_datum.errors.count, "error") %> prohibited this friend_datum from being saved:</h2>

      <ul>
        <% friend_datum.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group mb-3">
    <%= form.text_field :firtName,class:"form-control",placeholder:'First Name' %>
  </div>
  <div class="field form-group mb-3">
    <%= form.text_field :lastName,class:"form-control",placeholder:'Last Name' %>
  </div>

  <div class="field form-group mb-3">
    <%= form.text_field :email,class:"form-control",placeholder:'Email' %>
  </div>

  <div class="field form-group mb-3">
    <%= form.text_field :phone,class:"form-control",placeholder:'Phone Number' %>
  </div>

  <div class="field form-group mb-3">
    <%= form.text_field :user_id,id: :friend_data_user_id,class:"form-control",value: current_user.id, type: :hidden %>
  </div>
  <div class="actions mb-3">
    <%= form.submit class:'btn btn-secondary'%>
  </div>
<% end %>

rubyonrail/friend/app/views/friend_data/edit.html.erb
<h1>Editing Friend Datum</h1>

<%= render 'form', friend_datum: @friend_datum %>

<%= link_to 'Show', @friend_datum,class:'btn btn-secondary' %>
<%= link_to 'Back', friend_data_path,class:'btn btn-dark' %>

rubyonrail/friend/app/views/friend_data/index.html.erb
<h1>Friend Data</h1>

<table class="table table-striped table-hover">
  <thead class="table-dark">
    <tr>
      <th>Firtname</th>
      <th>Lastname</th>
      <th>Email</th>
      <th>Phone</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @friend_data.each do |friend_datum| %>
    <% if friend_datum.user == current_user%>

      <tr>
        <td><%= friend_datum.firtName %></td>
        <td><%= friend_datum.lastName %></td>
        <td><%= friend_datum.email %></td>
        <td><%= friend_datum.phone %></td>
        <td><%= link_to 'Show', friend_datum %></td>
        <td><%= link_to 'Edit', edit_friend_datum_path(friend_datum) %></td>
        <td><%= link_to 'Destroy', friend_datum, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Friend', new_friend_datum_path,class:'btn btn-secondary' %>

rubyonrail/friend/app/views/friend_data/new.html.erb
<h1>Add new Friend</h1>
<br />
<%= render 'form', friend_datum: @friend_datum %>

<%= link_to 'Back', friend_data_path,class:'btn btn-dark' %>

rubyonrail/friend/app/views/friend_data/show.html.erb
<style type="text/css">
    .jumbotron {
      padding: 4rem 2rem;
      margin-bottom: 2rem;
      background-color: var(--bs-light);
      border-radius: .3rem;  
    }
</style>
<div class="jumbotron">
  <h1 class="display-4">  
  <%= @friend_datum.firtName %>
  <%= @friend_datum.lastName %>
  </h1>
  <p class="lead"><%= @friend_datum.email %> | <%= @friend_datum.phone %></p>
  <br/>
  <br/>
  <hr class="my-4">
  
<%= link_to 'Edit', edit_friend_datum_path(@friend_datum),class:"btn btn-secondary" %>
<%= link_to 'Back', friend_data_path,class:"btn btn-dark" %>
</div>

rubyonrail/friend/app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <%= link_to 'Friend App' , root_path, class:"navbar-brand"%>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">

        <li class="nav-item">
          <%= link_to 'About Us' , home_about_path, class:"nav-link"%>
        </li>
     
       
        
        <% if user_signed_in?%>
          <li class="nav-item">
            <%= link_to 'Friends' , friend_data_path, class:"nav-link"%>
          </li>
          <li class="nav-item">
            <%= link_to 'Add Friend' , new_friend_datum_path, class:"nav-link"%>
          </li>
          <li class="nav-item">
            <%= link_to 'Sign Out' , destroy_user_session_path, method: :delete,class:"nav-link"%>
          </li>
          <li class="nav-item">
            <%= link_to 'Edit Profile' , edit_user_registration_path, class:"nav-link"%>
          </li>
       <% else %>
        <li class="nav-item">
            <%= link_to 'Sign In' , new_user_session_path, class:"nav-link"%>
          </li>
          <li class="nav-item">
            <%= link_to 'Sign Up' , new_user_registration_path, class:"nav-link"%>
          </li>
        <%  end %>
        
      </ul>
     
    </div>
  </div>
</nav>

rubyonrail/friend/app/views/home/about.html.erb
<h1>
    About Page
</h1>

rubyonrail/friend/app/views/home/index.html.erb
<h1>Hello world </h1>
This is my rails page

rubyonrail/friend/app/views/layouts/_alert.html.erb
<div class="alert alert-warning alert-dismissible fade show" role="alert">
    <%=notice%>
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>

rubyonrail/friend/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Friend</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'home/header' %>
    <div class="container">
      <% if notice%>
        <%= render 'layouts/alert'%>
      <% end %>
      <br />
      <%= yield %>
    </div>


    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
  </body>
</html>